name: IPWhiteList
version: 2.0
main: io.github.Earth1283.ipwhitelist.IPWhitelistPlugin
api-version: '1.21'
load: STARTUP
author: Earth1283
commands:
  ipwhitelist:
    description: Manage the IP whitelist
    usage: /ipwhitelist <add|remove|list> [ip]
    permission: ipwhitelist.admin
permissions:
  ipwhitelist.admin:
    description: Allows managing the IP whitelist
    default: op
  ipwhitelist.bypass:
    description: Bypasses the IP whitelist check
    default: false
